export const defaultImages = [
  {
    id: 'fGyFiV_Yobw',
    slug: 'a-view-of-a-forest-with-a-mountain-in-the-background-fGyFiV_Yobw',
    alternative_slugs: {
      en: 'a-view-of-a-forest-with-a-mountain-in-the-background-fGyFiV_Yobw',
      es: 'una-vista-de-un-bosque-con-una-montana-al-fondo-fGyFiV_Yobw',
      ja: '山を背景にした森の眺め-fGyFiV_Yobw',
      fr: 'une-vue-dune-foret-avec-une-montagne-en-arriere-plan-fGyFiV_Yobw',
      it: 'una-vista-di-una-foresta-con-una-montagna-sullo-sfondo-fGyFiV_Yobw',
      ko: '산을-배경으로-한-숲의-모습-fGyFiV_Yobw',
      de: 'blick-auf-einen-wald-mit-einem-berg-im-hintergrund-fGyFiV_Yobw',
      pt: 'uma-vista-de-uma-floresta-com-uma-montanha-ao-fundo-fGyFiV_Yobw',
    },
    created_at: '2023-06-11T12:21:12Z',
    updated_at: '2024-04-03T05:40:14Z',
    promoted_at: '2023-06-12T14:40:01Z',
    width: 7008,
    height: 4672,
    color: '#f3f3f3',
    blur_hash: 'L,HCM]E1WXog~qIoj[of%NWUj[j]',
    description: null,
    alt_description: 'a view of a forest with a mountain in the background',
    breadcrumbs: [
      {
        slug: 'images',
        title: '1,000,000+ Free Images',
        index: 0,
        type: 'landing_page',
      },
      {
        slug: 'feelings',
        title: 'Feelings Images',
        index: 1,
        type: 'landing_page',
      },
      {
        slug: 'cool',
        title: 'Cool Images & Photos',
        index: 2,
        type: 'landing_page',
      },
    ],
    urls: {
      raw: 'https://images.unsplash.com/photo-1686485231345-7e2808ed2f3b?ixid=M3w1OTQwMTR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTM4OTA2ODV8&ixlib=rb-4.0.3',
      full: 'https://images.unsplash.com/photo-1686485231345-7e2808ed2f3b?crop=entropy&cs=srgb&fm=jpg&ixid=M3w1OTQwMTR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTM4OTA2ODV8&ixlib=rb-4.0.3&q=85',
      regular:
        'https://images.unsplash.com/photo-1686485231345-7e2808ed2f3b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w1OTQwMTR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTM4OTA2ODV8&ixlib=rb-4.0.3&q=80&w=1080',
      small:
        'https://images.unsplash.com/photo-1686485231345-7e2808ed2f3b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w1OTQwMTR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTM4OTA2ODV8&ixlib=rb-4.0.3&q=80&w=400',
      thumb:
        'https://images.unsplash.com/photo-1686485231345-7e2808ed2f3b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w1OTQwMTR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTM4OTA2ODV8&ixlib=rb-4.0.3&q=80&w=200',
      small_s3:
        'https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1686485231345-7e2808ed2f3b',
    },
    links: {
      self: 'https://api.unsplash.com/photos/a-view-of-a-forest-with-a-mountain-in-the-background-fGyFiV_Yobw',
      html: 'https://unsplash.com/photos/a-view-of-a-forest-with-a-mountain-in-the-background-fGyFiV_Yobw',
      download:
        'https://unsplash.com/photos/fGyFiV_Yobw/download?ixid=M3w1OTQwMTR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTM4OTA2ODV8',
      download_location:
        'https://api.unsplash.com/photos/fGyFiV_Yobw/download?ixid=M3w1OTQwMTR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTM4OTA2ODV8',
    },
    likes: 179,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {
      travel: {
        status: 'rejected',
      },
      nature: {
        status: 'approved',
        approved_on: '2023-06-14T10:52:51Z',
      },
      wallpapers: {
        status: 'rejected',
      },
    },
    asset_type: 'photo',
    user: {
      id: '70vThSO-MrA',
      updated_at: '2024-04-21T06:57:18Z',
      username: 'dbr0vskyi',
      name: 'Yevhenii Dubrovskyi',
      first_name: 'Yevhenii',
      last_name: 'Dubrovskyi',
      twitter_username: 'dbr0vskyi',
      portfolio_url: null,
      bio: 'Photographer at heart, explorer by lens. Discovering beauty in all its forms. Join me on a journey through my viewfinder.',
      location: null,
      links: {
        self: 'https://api.unsplash.com/users/dbr0vskyi',
        html: 'https://unsplash.com/@dbr0vskyi',
        photos: 'https://api.unsplash.com/users/dbr0vskyi/photos',
        likes: 'https://api.unsplash.com/users/dbr0vskyi/likes',
        portfolio: 'https://api.unsplash.com/users/dbr0vskyi/portfolio',
        following: 'https://api.unsplash.com/users/dbr0vskyi/following',
        followers: 'https://api.unsplash.com/users/dbr0vskyi/followers',
      },
      profile_image: {
        small:
          'https://images.unsplash.com/profile-1667829222787-6bedb3699ae4?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32',
        medium:
          'https://images.unsplash.com/profile-1667829222787-6bedb3699ae4?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64',
        large:
          'https://images.unsplash.com/profile-1667829222787-6bedb3699ae4?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128',
      },
      instagram_username: null,
      total_collections: 15,
      total_likes: 98,
      total_photos: 203,
      total_promoted_photos: 34,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: true,
      social: {
        instagram_username: null,
        portfolio_url: null,
        twitter_username: 'dbr0vskyi',
        paypal_email: null,
      },
    },
    exif: {
      make: 'SONY',
      model: 'ILCE-7M4',
      name: 'SONY, ILCE-7M4',
      exposure_time: '1/500',
      aperture: '4.0',
      focal_length: '35.0',
      iso: 100,
    },
    location: {
      name: 'Gęsia Szyja, Poland',
      city: null,
      country: 'Poland',
      position: {
        latitude: 49.259722,
        longitude: 20.077778,
      },
    },
    views: 5854306,
    downloads: 26890,
  },
  {
    id: 'YeoBujE0RmM',
    slug: 'the-night-sky-is-reflected-in-a-body-of-water-YeoBujE0RmM',
    alternative_slugs: {
      en: 'the-night-sky-is-reflected-in-a-body-of-water-YeoBujE0RmM',
      es: 'el-cielo-nocturno-se-refleja-en-un-cuerpo-de-agua-YeoBujE0RmM',
      ja: '水面に映る夜空-YeoBujE0RmM',
      fr: 'le-ciel-nocturne-se-reflete-dans-un-plan-deau-YeoBujE0RmM',
      it: 'il-cielo-notturno-si-riflette-in-uno-specchio-dacqua-YeoBujE0RmM',
      ko: '밤하늘이-물에-반사됩니다-YeoBujE0RmM',
      de: 'der-nachthimmel-spiegelt-sich-in-einem-gewasser-YeoBujE0RmM',
      pt: 'o-ceu-noturno-e-refletido-em-um-corpo-de-agua-YeoBujE0RmM',
    },
    created_at: '2023-10-27T13:51:25Z',
    updated_at: '2024-03-23T07:35:59Z',
    promoted_at: '2023-10-31T08:32:01Z',
    width: 5472,
    height: 3648,
    color: '#262626',
    blur_hash: 'L12$T@x]IARj?vt7V@WVMxRjx]oz',
    description: null,
    alt_description: 'the night sky is reflected in a body of water',
    breadcrumbs: [],
    urls: {
      raw: 'https://images.unsplash.com/photo-1698414675352-8954e00c8553?ixid=M3w1OTQwMTR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTM4OTA2ODV8&ixlib=rb-4.0.3',
      full: 'https://images.unsplash.com/photo-1698414675352-8954e00c8553?crop=entropy&cs=srgb&fm=jpg&ixid=M3w1OTQwMTR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTM4OTA2ODV8&ixlib=rb-4.0.3&q=85',
      regular:
        'https://images.unsplash.com/photo-1698414675352-8954e00c8553?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w1OTQwMTR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTM4OTA2ODV8&ixlib=rb-4.0.3&q=80&w=1080',
      small:
        'https://images.unsplash.com/photo-1698414675352-8954e00c8553?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w1OTQwMTR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTM4OTA2ODV8&ixlib=rb-4.0.3&q=80&w=400',
      thumb:
        'https://images.unsplash.com/photo-1698414675352-8954e00c8553?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w1OTQwMTR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTM4OTA2ODV8&ixlib=rb-4.0.3&q=80&w=200',
      small_s3:
        'https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1698414675352-8954e00c8553',
    },
    links: {
      self: 'https://api.unsplash.com/photos/the-night-sky-is-reflected-in-a-body-of-water-YeoBujE0RmM',
      html: 'https://unsplash.com/photos/the-night-sky-is-reflected-in-a-body-of-water-YeoBujE0RmM',
      download:
        'https://unsplash.com/photos/YeoBujE0RmM/download?ixid=M3w1OTQwMTR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTM4OTA2ODV8',
      download_location:
        'https://api.unsplash.com/photos/YeoBujE0RmM/download?ixid=M3w1OTQwMTR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTM4OTA2ODV8',
    },
    likes: 85,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {},
    asset_type: 'photo',
    user: {
      id: 'XZDJrfKzdWY',
      updated_at: '2024-04-23T16:32:05Z',
      username: 'eberhardgross',
      name: 'eberhard 🖐 grossgasteiger',
      first_name: 'eberhard 🖐',
      last_name: 'grossgasteiger',
      twitter_username: null,
      portfolio_url: 'https://narrateography.art',
      bio: 'Photography is so incredibly complex, although seemingly simplistic.',
      location: 'South Tyrol, Italy',
      links: {
        self: 'https://api.unsplash.com/users/eberhardgross',
        html: 'https://unsplash.com/@eberhardgross',
        photos: 'https://api.unsplash.com/users/eberhardgross/photos',
        likes: 'https://api.unsplash.com/users/eberhardgross/likes',
        portfolio: 'https://api.unsplash.com/users/eberhardgross/portfolio',
        following: 'https://api.unsplash.com/users/eberhardgross/following',
        followers: 'https://api.unsplash.com/users/eberhardgross/followers',
      },
      profile_image: {
        small:
          'https://images.unsplash.com/profile-1593541755358-41ff2a4e41efimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32',
        medium:
          'https://images.unsplash.com/profile-1593541755358-41ff2a4e41efimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64',
        large:
          'https://images.unsplash.com/profile-1593541755358-41ff2a4e41efimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128',
      },
      instagram_username: 'eberhard_grossgasteiger',
      total_collections: 6,
      total_likes: 4747,
      total_photos: 2021,
      total_promoted_photos: 1800,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: false,
      social: {
        instagram_username: 'eberhard_grossgasteiger',
        portfolio_url: 'https://narrateography.art',
        twitter_username: null,
        paypal_email: null,
      },
    },
    exif: {
      make: 'SONY',
      model: 'ILCE-7RM3',
      name: 'SONY, ILCE-7RM3',
      exposure_time: null,
      aperture: '4',
      focal_length: '18.0',
      iso: 400,
    },
    location: {
      name: null,
      city: null,
      country: null,
      position: {
        latitude: 0,
        longitude: 0,
      },
    },
    views: 2612203,
    downloads: 22413,
  },
  {
    id: 'hCi8_4Rg7JQ',
    slug: 'a-white-square-object-with-blue-balls-on-it-hCi8_4Rg7JQ',
    alternative_slugs: {
      en: 'a-white-square-object-with-blue-balls-on-it-hCi8_4Rg7JQ',
      es: 'un-objeto-cuadrado-blanco-con-bolas-azules-hCi8_4Rg7JQ',
      ja: '青いボールが付いた白い正方形のオブジェクト-hCi8_4Rg7JQ',
      fr: 'un-objet-carre-blanc-avec-des-boules-bleues-dessus-hCi8_4Rg7JQ',
      it: 'un-oggetto-quadrato-bianco-con-palline-blu-su-di-esso-hCi8_4Rg7JQ',
      ko: '파란색-공이-있는-흰색-사각형-개체-hCi8_4Rg7JQ',
      de: 'ein-weisses-quadratisches-objekt-mit-blauen-kugeln-darauf-hCi8_4Rg7JQ',
      pt: 'um-objeto-quadrado-branco-com-bolas-azuis-sobre-ele-hCi8_4Rg7JQ',
    },
    created_at: '2022-10-18T09:35:09Z',
    updated_at: '2024-04-21T23:48:46Z',
    promoted_at: '2022-11-25T14:08:48Z',
    width: 2100,
    height: 2970,
    color: '#c0d9d9',
    blur_hash: 'LDKx^{t7tlof~VNGs8aynis:aeae',
    description: null,
    alt_description: 'a white square object with blue balls on it',
    breadcrumbs: [],
    urls: {
      raw: 'https://images.unsplash.com/photo-1666085575722-bdf8a510c2c1?ixid=M3w1OTQwMTR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTM4OTA2ODV8&ixlib=rb-4.0.3',
      full: 'https://images.unsplash.com/photo-1666085575722-bdf8a510c2c1?crop=entropy&cs=srgb&fm=jpg&ixid=M3w1OTQwMTR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTM4OTA2ODV8&ixlib=rb-4.0.3&q=85',
      regular:
        'https://images.unsplash.com/photo-1666085575722-bdf8a510c2c1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w1OTQwMTR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTM4OTA2ODV8&ixlib=rb-4.0.3&q=80&w=1080',
      small:
        'https://images.unsplash.com/photo-1666085575722-bdf8a510c2c1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w1OTQwMTR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTM4OTA2ODV8&ixlib=rb-4.0.3&q=80&w=400',
      thumb:
        'https://images.unsplash.com/photo-1666085575722-bdf8a510c2c1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w1OTQwMTR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTM4OTA2ODV8&ixlib=rb-4.0.3&q=80&w=200',
      small_s3:
        'https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1666085575722-bdf8a510c2c1',
    },
    links: {
      self: 'https://api.unsplash.com/photos/a-white-square-object-with-blue-balls-on-it-hCi8_4Rg7JQ',
      html: 'https://unsplash.com/photos/a-white-square-object-with-blue-balls-on-it-hCi8_4Rg7JQ',
      download:
        'https://unsplash.com/photos/hCi8_4Rg7JQ/download?ixid=M3w1OTQwMTR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTM4OTA2ODV8',
      download_location:
        'https://api.unsplash.com/photos/hCi8_4Rg7JQ/download?ixid=M3w1OTQwMTR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTM4OTA2ODV8',
    },
    likes: 285,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {
      '3d-renders': {
        status: 'approved',
        approved_on: '2022-10-26T15:21:32Z',
      },
    },
    asset_type: 'photo',
    user: {
      id: '0FbO9-PHiw8',
      updated_at: '2024-03-21T11:11:38Z',
      username: 'aligntowardsspine',
      name: 'Align Towards Spine',
      first_name: 'Align Towards Spine',
      last_name: null,
      twitter_username: null,
      portfolio_url: null,
      bio: null,
      location: 'Belgium',
      links: {
        self: 'https://api.unsplash.com/users/aligntowardsspine',
        html: 'https://unsplash.com/@aligntowardsspine',
        photos: 'https://api.unsplash.com/users/aligntowardsspine/photos',
        likes: 'https://api.unsplash.com/users/aligntowardsspine/likes',
        portfolio: 'https://api.unsplash.com/users/aligntowardsspine/portfolio',
        following: 'https://api.unsplash.com/users/aligntowardsspine/following',
        followers: 'https://api.unsplash.com/users/aligntowardsspine/followers',
      },
      profile_image: {
        small:
          'https://images.unsplash.com/profile-1666085863947-09ed2f96521bimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32',
        medium:
          'https://images.unsplash.com/profile-1666085863947-09ed2f96521bimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64',
        large:
          'https://images.unsplash.com/profile-1666085863947-09ed2f96521bimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128',
      },
      instagram_username: 'aligntowardsspine',
      total_collections: 0,
      total_likes: 28,
      total_photos: 23,
      total_promoted_photos: 13,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: true,
      social: {
        instagram_username: 'aligntowardsspine',
        portfolio_url: null,
        twitter_username: null,
        paypal_email: null,
      },
    },
    exif: {
      make: null,
      model: null,
      name: null,
      exposure_time: null,
      aperture: null,
      focal_length: null,
      iso: null,
    },
    location: {
      name: null,
      city: null,
      country: null,
      position: {
        latitude: null,
        longitude: null,
      },
    },
    views: 3930576,
    downloads: 41528,
  },
  {
    id: 'Cz7a9Snlnmw',
    slug: 'snow-covered-mountaan-under-gray-sky-Cz7a9Snlnmw',
    alternative_slugs: {
      en: 'snow-covered-mountaan-under-gray-sky-Cz7a9Snlnmw',
      es: 'monte-cubierto-de-nieve-bajo-el-cielo-gris-Cz7a9Snlnmw',
      ja: '灰色の空の下で雪に覆われたマウントターン-Cz7a9Snlnmw',
      fr: 'montagne-enneigee-sous-ciel-gris-Cz7a9Snlnmw',
      it: 'monte-coperto-di-neve-sotto-il-cielo-grigio-Cz7a9Snlnmw',
      ko: '회색-하늘-아래-눈-덮인-mountaan-Cz7a9Snlnmw',
      de: 'schneebedeckter-berg-unter-grauem-himmel-Cz7a9Snlnmw',
      pt: 'neve-coberta-de-mountaan-sob-ceu-cinzento-Cz7a9Snlnmw',
    },
    created_at: '2017-03-09T12:06:20Z',
    updated_at: '2024-04-01T19:03:49Z',
    promoted_at: '2017-03-09T12:06:20Z',
    width: 4347,
    height: 3006,
    color: '#8c8c8c',
    blur_hash: 'LZG+K?t6M{t7-;R*Rka|0Kt7t7NG',
    description: 'Life is either a daring adventure or nothing - Helen Keller',
    alt_description: 'snow covered mountaan under gray sky',
    breadcrumbs: [],
    urls: {
      raw: 'https://images.unsplash.com/photo-1489060887344-f3a2c715dbe5?ixid=M3w1OTQwMTR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTM4OTA2ODV8&ixlib=rb-4.0.3',
      full: 'https://images.unsplash.com/photo-1489060887344-f3a2c715dbe5?crop=entropy&cs=srgb&fm=jpg&ixid=M3w1OTQwMTR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTM4OTA2ODV8&ixlib=rb-4.0.3&q=85',
      regular:
        'https://images.unsplash.com/photo-1489060887344-f3a2c715dbe5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w1OTQwMTR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTM4OTA2ODV8&ixlib=rb-4.0.3&q=80&w=1080',
      small:
        'https://images.unsplash.com/photo-1489060887344-f3a2c715dbe5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w1OTQwMTR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTM4OTA2ODV8&ixlib=rb-4.0.3&q=80&w=400',
      thumb:
        'https://images.unsplash.com/photo-1489060887344-f3a2c715dbe5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w1OTQwMTR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTM4OTA2ODV8&ixlib=rb-4.0.3&q=80&w=200',
      small_s3:
        'https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1489060887344-f3a2c715dbe5',
    },
    links: {
      self: 'https://api.unsplash.com/photos/snow-covered-mountaan-under-gray-sky-Cz7a9Snlnmw',
      html: 'https://unsplash.com/photos/snow-covered-mountaan-under-gray-sky-Cz7a9Snlnmw',
      download:
        'https://unsplash.com/photos/Cz7a9Snlnmw/download?ixid=M3w1OTQwMTR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTM4OTA2ODV8',
      download_location:
        'https://api.unsplash.com/photos/Cz7a9Snlnmw/download?ixid=M3w1OTQwMTR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTM4OTA2ODV8',
    },
    likes: 342,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {},
    asset_type: 'photo',
    user: {
      id: 'zq-UW5M0mpI',
      updated_at: '2024-04-22T18:31:16Z',
      username: 'christopher__burns',
      name: 'Christopher Burns',
      first_name: 'Christopher',
      last_name: 'Burns',
      twitter_username: null,
      portfolio_url: 'https://www.instagram.com/christopher__burns/',
      bio: 'London // Sydney \r\n',
      location: null,
      links: {
        self: 'https://api.unsplash.com/users/christopher__burns',
        html: 'https://unsplash.com/@christopher__burns',
        photos: 'https://api.unsplash.com/users/christopher__burns/photos',
        likes: 'https://api.unsplash.com/users/christopher__burns/likes',
        portfolio:
          'https://api.unsplash.com/users/christopher__burns/portfolio',
        following:
          'https://api.unsplash.com/users/christopher__burns/following',
        followers:
          'https://api.unsplash.com/users/christopher__burns/followers',
      },
      profile_image: {
        small:
          'https://images.unsplash.com/profile-1523277534788-b3a17d62775e?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32',
        medium:
          'https://images.unsplash.com/profile-1523277534788-b3a17d62775e?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64',
        large:
          'https://images.unsplash.com/profile-1523277534788-b3a17d62775e?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128',
      },
      instagram_username: 'christopher__burns',
      total_collections: 3,
      total_likes: 35,
      total_photos: 125,
      total_promoted_photos: 73,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: true,
      social: {
        instagram_username: 'christopher__burns',
        portfolio_url: 'https://www.instagram.com/christopher__burns/',
        twitter_username: null,
        paypal_email: null,
      },
    },
    exif: {
      make: 'Canon',
      model: 'Canon EOS 5D Mark III',
      name: 'Canon, EOS 5D Mark III',
      exposure_time: '1/640',
      aperture: '6.3',
      focal_length: '85.0',
      iso: 200,
    },
    location: {
      name: 'Patagonia',
      city: null,
      country: null,
      position: {
        latitude: -41.8101472,
        longitude: -68.9062689,
      },
    },
    views: 6499698,
    downloads: 6502,
  },
  {
    id: '37zRH33eO60',
    slug: 'orange-boat-37zRH33eO60',
    alternative_slugs: {
      en: 'orange-boat-37zRH33eO60',
      es: 'barco-naranja-37zRH33eO60',
      ja: 'オレンジボート-37zRH33eO60',
      fr: 'bateau-orange-37zRH33eO60',
      it: 'barca-arancione-37zRH33eO60',
      ko: '오렌지-보트-37zRH33eO60',
      de: 'orangefarbenes-boot-37zRH33eO60',
      pt: 'barco-laranja-37zRH33eO60',
    },
    created_at: '2019-07-28T05:12:04Z',
    updated_at: '2024-04-15T00:21:01Z',
    promoted_at: '2019-07-28T08:11:43Z',
    width: 4981,
    height: 3321,
    color: '#262626',
    blur_hash: 'LaECtVR+D%xa~qV@Mxof?bRjM{ay',
    description: null,
    alt_description: 'orange boat',
    breadcrumbs: [],
    urls: {
      raw: 'https://images.unsplash.com/photo-1564290713859-31aa297381fa?ixid=M3w1OTQwMTR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTM4OTA2ODV8&ixlib=rb-4.0.3',
      full: 'https://images.unsplash.com/photo-1564290713859-31aa297381fa?crop=entropy&cs=srgb&fm=jpg&ixid=M3w1OTQwMTR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTM4OTA2ODV8&ixlib=rb-4.0.3&q=85',
      regular:
        'https://images.unsplash.com/photo-1564290713859-31aa297381fa?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w1OTQwMTR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTM4OTA2ODV8&ixlib=rb-4.0.3&q=80&w=1080',
      small:
        'https://images.unsplash.com/photo-1564290713859-31aa297381fa?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w1OTQwMTR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTM4OTA2ODV8&ixlib=rb-4.0.3&q=80&w=400',
      thumb:
        'https://images.unsplash.com/photo-1564290713859-31aa297381fa?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w1OTQwMTR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTM4OTA2ODV8&ixlib=rb-4.0.3&q=80&w=200',
      small_s3:
        'https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1564290713859-31aa297381fa',
    },
    links: {
      self: 'https://api.unsplash.com/photos/orange-boat-37zRH33eO60',
      html: 'https://unsplash.com/photos/orange-boat-37zRH33eO60',
      download:
        'https://unsplash.com/photos/37zRH33eO60/download?ixid=M3w1OTQwMTR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTM4OTA2ODV8',
      download_location:
        'https://api.unsplash.com/photos/37zRH33eO60/download?ixid=M3w1OTQwMTR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTM4OTA2ODV8',
    },
    likes: 109,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {},
    asset_type: 'photo',
    user: {
      id: 'r2Pak86KiYk',
      updated_at: '2024-04-19T06:01:44Z',
      username: 'dmtrdon',
      name: 'Dimitar Donovski',
      first_name: 'Dimitar',
      last_name: 'Donovski',
      twitter_username: 'DimitarDonovski',
      portfolio_url: null,
      bio: 'were it so easy',
      location: 'Indianapolis, IN',
      links: {
        self: 'https://api.unsplash.com/users/dmtrdon',
        html: 'https://unsplash.com/@dmtrdon',
        photos: 'https://api.unsplash.com/users/dmtrdon/photos',
        likes: 'https://api.unsplash.com/users/dmtrdon/likes',
        portfolio: 'https://api.unsplash.com/users/dmtrdon/portfolio',
        following: 'https://api.unsplash.com/users/dmtrdon/following',
        followers: 'https://api.unsplash.com/users/dmtrdon/followers',
      },
      profile_image: {
        small:
          'https://images.unsplash.com/profile-1628382685995-bb585a40b36dimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32',
        medium:
          'https://images.unsplash.com/profile-1628382685995-bb585a40b36dimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64',
        large:
          'https://images.unsplash.com/profile-1628382685995-bb585a40b36dimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128',
      },
      instagram_username: 'dimitardon',
      total_collections: 4,
      total_likes: 266,
      total_photos: 117,
      total_promoted_photos: 53,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: false,
      social: {
        instagram_username: 'dimitardon',
        portfolio_url: null,
        twitter_username: 'DimitarDonovski',
        paypal_email: null,
      },
    },
    exif: {
      make: 'Canon',
      model: 'Canon EOS Rebel T6',
      name: 'Canon, EOS Rebel T6',
      exposure_time: '1/100',
      aperture: '8.0',
      focal_length: '18.0',
      iso: 100,
    },
    location: {
      name: 'Moraine Lake, Banff, Canada',
      city: 'Banff',
      country: 'Canada',
      position: {
        latitude: null,
        longitude: null,
      },
    },
    views: 11799394,
    downloads: 8247,
  },
  {
    id: 'QyNM4jOFiqg',
    slug: 'water-crashed-through-rocks-QyNM4jOFiqg',
    alternative_slugs: {
      en: 'water-crashed-through-rocks-QyNM4jOFiqg',
      es: 'el-agua-se-estrello-contra-las-rocas-QyNM4jOFiqg',
      ja: '水が岩を突き破る-QyNM4jOFiqg',
      fr: 'leau-sest-ecrasee-a-travers-les-rochers-QyNM4jOFiqg',
      it: 'lacqua-si-e-schiantata-attraverso-le-rocce-QyNM4jOFiqg',
      ko: '바위-사이로-물이-부딪쳤다-QyNM4jOFiqg',
      de: 'wasser-krachte-durch-felsen-QyNM4jOFiqg',
      pt: 'agua-caiu-em-rochas-QyNM4jOFiqg',
    },
    created_at: '2019-08-21T23:58:40Z',
    updated_at: '2024-04-22T21:19:58Z',
    promoted_at: '2019-08-22T08:23:12Z',
    width: 3648,
    height: 5472,
    color: '#f3f3f3',
    blur_hash: 'LiOplQRjRjof_Nayj[j[?bxuoefQ',
    description: null,
    alt_description: 'water crashed through rocks',
    breadcrumbs: [],
    urls: {
      raw: 'https://images.unsplash.com/photo-1566431756727-c8e9212d0445?ixid=M3w1OTQwMTR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTM4OTA2ODV8&ixlib=rb-4.0.3',
      full: 'https://images.unsplash.com/photo-1566431756727-c8e9212d0445?crop=entropy&cs=srgb&fm=jpg&ixid=M3w1OTQwMTR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTM4OTA2ODV8&ixlib=rb-4.0.3&q=85',
      regular:
        'https://images.unsplash.com/photo-1566431756727-c8e9212d0445?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w1OTQwMTR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTM4OTA2ODV8&ixlib=rb-4.0.3&q=80&w=1080',
      small:
        'https://images.unsplash.com/photo-1566431756727-c8e9212d0445?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w1OTQwMTR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTM4OTA2ODV8&ixlib=rb-4.0.3&q=80&w=400',
      thumb:
        'https://images.unsplash.com/photo-1566431756727-c8e9212d0445?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w1OTQwMTR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTM4OTA2ODV8&ixlib=rb-4.0.3&q=80&w=200',
      small_s3:
        'https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1566431756727-c8e9212d0445',
    },
    links: {
      self: 'https://api.unsplash.com/photos/water-crashed-through-rocks-QyNM4jOFiqg',
      html: 'https://unsplash.com/photos/water-crashed-through-rocks-QyNM4jOFiqg',
      download:
        'https://unsplash.com/photos/QyNM4jOFiqg/download?ixid=M3w1OTQwMTR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTM4OTA2ODV8',
      download_location:
        'https://api.unsplash.com/photos/QyNM4jOFiqg/download?ixid=M3w1OTQwMTR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTM4OTA2ODV8',
    },
    likes: 211,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {},
    asset_type: 'photo',
    user: {
      id: '5-ZZGSepYuk',
      updated_at: '2024-04-16T18:29:44Z',
      username: 'jonathanborba',
      name: 'Jonathan Borba',
      first_name: 'Jonathan',
      last_name: 'Borba',
      twitter_username: null,
      portfolio_url: 'https://jonathanborba.46graus.com/',
      bio: '✈️ I travel the world photographing!\r\n 🏢 Founder: JSB Company | @jsbco 🏆 2B Views on Unsplash',
      location: 'Brazil',
      links: {
        self: 'https://api.unsplash.com/users/jonathanborba',
        html: 'https://unsplash.com/@jonathanborba',
        photos: 'https://api.unsplash.com/users/jonathanborba/photos',
        likes: 'https://api.unsplash.com/users/jonathanborba/likes',
        portfolio: 'https://api.unsplash.com/users/jonathanborba/portfolio',
        following: 'https://api.unsplash.com/users/jonathanborba/following',
        followers: 'https://api.unsplash.com/users/jonathanborba/followers',
      },
      profile_image: {
        small:
          'https://images.unsplash.com/profile-1649780208872-f20801c00700image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32',
        medium:
          'https://images.unsplash.com/profile-1649780208872-f20801c00700image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64',
        large:
          'https://images.unsplash.com/profile-1649780208872-f20801c00700image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128',
      },
      instagram_username: 'jonathansborba',
      total_collections: 43,
      total_likes: 6394,
      total_photos: 3006,
      total_promoted_photos: 911,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: true,
      social: {
        instagram_username: 'jonathansborba',
        portfolio_url: 'https://jonathanborba.46graus.com/',
        twitter_username: null,
        paypal_email: null,
      },
    },
    exif: {
      make: 'Canon',
      model: 'Canon EOS 6D',
      name: 'Canon, EOS 6D',
      exposure_time: '1/500',
      aperture: '3.2',
      focal_length: '135.0',
      iso: 1600,
    },
    location: {
      name: null,
      city: null,
      country: null,
      position: {
        latitude: null,
        longitude: null,
      },
    },
    views: 11550476,
    downloads: 9189,
  },
  {
    id: 'F4-j7I4sFBU',
    slug: 'silhouette-of-mountain-F4-j7I4sFBU',
    alternative_slugs: {
      en: 'silhouette-of-mountain-F4-j7I4sFBU',
      es: 'silueta-de-montana-F4-j7I4sFBU',
      ja: '山のシルエット-F4-j7I4sFBU',
      fr: 'silhouette-de-montagne-F4-j7I4sFBU',
      it: 'silhouette-di-montagna-F4-j7I4sFBU',
      ko: '산의-실루엣-F4-j7I4sFBU',
      de: 'silhouette-des-berges-F4-j7I4sFBU',
      pt: 'silhueta-da-montanha-F4-j7I4sFBU',
    },
    created_at: '2018-11-25T00:51:55Z',
    updated_at: '2024-04-02T02:03:55Z',
    promoted_at: '2018-11-25T08:04:06Z',
    width: 5760,
    height: 3840,
    color: '#592626',
    blur_hash: 'LqFzo$t3odR,sCWCazoK0*R,WWod',
    description: 'Last Forever',
    alt_description: 'silhouette of mountain',
    breadcrumbs: [],
    urls: {
      raw: 'https://images.unsplash.com/photo-1543107097-ffe418c8d0f0?ixid=M3w1OTQwMTR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTM4OTA2ODV8&ixlib=rb-4.0.3',
      full: 'https://images.unsplash.com/photo-1543107097-ffe418c8d0f0?crop=entropy&cs=srgb&fm=jpg&ixid=M3w1OTQwMTR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTM4OTA2ODV8&ixlib=rb-4.0.3&q=85',
      regular:
        'https://images.unsplash.com/photo-1543107097-ffe418c8d0f0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w1OTQwMTR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTM4OTA2ODV8&ixlib=rb-4.0.3&q=80&w=1080',
      small:
        'https://images.unsplash.com/photo-1543107097-ffe418c8d0f0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w1OTQwMTR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTM4OTA2ODV8&ixlib=rb-4.0.3&q=80&w=400',
      thumb:
        'https://images.unsplash.com/photo-1543107097-ffe418c8d0f0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w1OTQwMTR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTM4OTA2ODV8&ixlib=rb-4.0.3&q=80&w=200',
      small_s3:
        'https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1543107097-ffe418c8d0f0',
    },
    links: {
      self: 'https://api.unsplash.com/photos/silhouette-of-mountain-F4-j7I4sFBU',
      html: 'https://unsplash.com/photos/silhouette-of-mountain-F4-j7I4sFBU',
      download:
        'https://unsplash.com/photos/F4-j7I4sFBU/download?ixid=M3w1OTQwMTR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTM4OTA2ODV8',
      download_location:
        'https://api.unsplash.com/photos/F4-j7I4sFBU/download?ixid=M3w1OTQwMTR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTM4OTA2ODV8',
    },
    likes: 185,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {
      wallpapers: {
        status: 'approved',
        approved_on: '2020-04-06T14:20:09Z',
      },
      nature: {
        status: 'approved',
        approved_on: '2023-12-29T20:16:35Z',
      },
    },
    asset_type: 'photo',
    user: {
      id: 'uMJXuywXLiU',
      updated_at: '2024-04-19T20:32:54Z',
      username: 'iamthedave',
      name: 'Dave Hoefler',
      first_name: 'Dave',
      last_name: 'Hoefler',
      twitter_username: null,
      portfolio_url: 'https://www.davehoefler.com/',
      bio: 'I like nature.',
      location: null,
      links: {
        self: 'https://api.unsplash.com/users/iamthedave',
        html: 'https://unsplash.com/@iamthedave',
        photos: 'https://api.unsplash.com/users/iamthedave/photos',
        likes: 'https://api.unsplash.com/users/iamthedave/likes',
        portfolio: 'https://api.unsplash.com/users/iamthedave/portfolio',
        following: 'https://api.unsplash.com/users/iamthedave/following',
        followers: 'https://api.unsplash.com/users/iamthedave/followers',
      },
      profile_image: {
        small:
          'https://images.unsplash.com/profile-1690398228733-ea9c81a6ad82image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32',
        medium:
          'https://images.unsplash.com/profile-1690398228733-ea9c81a6ad82image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64',
        large:
          'https://images.unsplash.com/profile-1690398228733-ea9c81a6ad82image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128',
      },
      instagram_username: 'just_midwest_rock',
      total_collections: 0,
      total_likes: 176,
      total_photos: 985,
      total_promoted_photos: 426,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: true,
      social: {
        instagram_username: 'just_midwest_rock',
        portfolio_url: 'https://www.davehoefler.com/',
        twitter_username: null,
        paypal_email: null,
      },
    },
    exif: {
      make: 'Canon',
      model: 'Canon EOS 5D Mark III',
      name: 'Canon, EOS 5D Mark III',
      exposure_time: '40',
      aperture: '11.0',
      focal_length: '400.0',
      iso: 100,
    },
    location: {
      name: 'Bandon, OR, US',
      city: 'Bandon',
      country: 'US',
      position: {
        latitude: null,
        longitude: null,
      },
    },
    views: 16067339,
    downloads: 36970,
  },
  {
    id: 'ugnrXk1129g',
    slug: 'aerial-photo-of-green-trees-ugnrXk1129g',
    alternative_slugs: {
      en: 'aerial-photo-of-green-trees-ugnrXk1129g',
      es: 'foto-aerea-de-arboles-verdes-ugnrXk1129g',
      ja: '緑の木々の航空写真-ugnrXk1129g',
      fr: 'photo-aerienne-darbres-verts-ugnrXk1129g',
      it: 'foto-aerea-di-alberi-verdi-ugnrXk1129g',
      ko: '푸른-나무의-항공-사진-ugnrXk1129g',
      de: 'luftaufnahme-von-grunen-baumen-ugnrXk1129g',
      pt: 'foto-aerea-de-arvores-verdes-ugnrXk1129g',
    },
    created_at: '2018-11-15T09:40:42Z',
    updated_at: '2024-04-23T12:12:20Z',
    promoted_at: '2018-11-15T09:49:09Z',
    width: 4288,
    height: 2848,
    color: '#d9d9d9',
    blur_hash: 'L*GSiZj[IUoM~qkBNGj[-pj[ofay',
    description:
      'This photo was taken in the high mountains of Adjara, Georgia, while I was doing my project there. It was summer, but the temperature didn’t feel like it. I spent most of my days standing in front of this amazing view, thinking about the life that was waiting for me back in capital. Suddenly, I  had a very strong desire to talk with the fog. Loudly. Thought it had many stories to tell too.',
    alt_description: 'aerial photo of green trees',
    breadcrumbs: [
      {
        slug: 'images',
        title: '1,000,000+ Free Images',
        index: 0,
        type: 'landing_page',
      },
      {
        slug: 'nature',
        title: 'Nature Images',
        index: 1,
        type: 'landing_page',
      },
    ],
    urls: {
      raw: 'https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?ixid=M3w1OTQwMTR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTM4OTA2ODV8&ixlib=rb-4.0.3',
      full: 'https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?crop=entropy&cs=srgb&fm=jpg&ixid=M3w1OTQwMTR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTM4OTA2ODV8&ixlib=rb-4.0.3&q=85',
      regular:
        'https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w1OTQwMTR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTM4OTA2ODV8&ixlib=rb-4.0.3&q=80&w=1080',
      small:
        'https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w1OTQwMTR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTM4OTA2ODV8&ixlib=rb-4.0.3&q=80&w=400',
      thumb:
        'https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w1OTQwMTR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTM4OTA2ODV8&ixlib=rb-4.0.3&q=80&w=200',
      small_s3:
        'https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1542273917363-3b1817f69a2d',
    },
    links: {
      self: 'https://api.unsplash.com/photos/aerial-photo-of-green-trees-ugnrXk1129g',
      html: 'https://unsplash.com/photos/aerial-photo-of-green-trees-ugnrXk1129g',
      download:
        'https://unsplash.com/photos/ugnrXk1129g/download?ixid=M3w1OTQwMTR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTM4OTA2ODV8',
      download_location:
        'https://api.unsplash.com/photos/ugnrXk1129g/download?ixid=M3w1OTQwMTR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTM4OTA2ODV8',
    },
    likes: 2934,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {
      wallpapers: {
        status: 'approved',
        approved_on: '2021-05-14T13:20:22Z',
      },
      nature: {
        status: 'approved',
        approved_on: '2020-04-06T14:20:12Z',
      },
    },
    asset_type: 'photo',
    user: {
      id: 'YevwEgUf1do',
      updated_at: '2024-03-18T15:02:38Z',
      username: 'maritaextrabold',
      name: 'Marita Kavelashvili',
      first_name: 'Marita',
      last_name: 'Kavelashvili',
      twitter_username: null,
      portfolio_url: null,
      bio: null,
      location: 'Tbilisi,Georgia',
      links: {
        self: 'https://api.unsplash.com/users/maritaextrabold',
        html: 'https://unsplash.com/@maritaextrabold',
        photos: 'https://api.unsplash.com/users/maritaextrabold/photos',
        likes: 'https://api.unsplash.com/users/maritaextrabold/likes',
        portfolio: 'https://api.unsplash.com/users/maritaextrabold/portfolio',
        following: 'https://api.unsplash.com/users/maritaextrabold/following',
        followers: 'https://api.unsplash.com/users/maritaextrabold/followers',
      },
      profile_image: {
        small:
          'https://images.unsplash.com/profile-1542273769119-89bf9760a424?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32',
        medium:
          'https://images.unsplash.com/profile-1542273769119-89bf9760a424?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64',
        large:
          'https://images.unsplash.com/profile-1542273769119-89bf9760a424?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128',
      },
      instagram_username: 'maritaextrabold',
      total_collections: 1,
      total_likes: 0,
      total_photos: 1,
      total_promoted_photos: 3,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: true,
      social: {
        instagram_username: 'maritaextrabold',
        portfolio_url: null,
        twitter_username: null,
        paypal_email: null,
      },
    },
    exif: {
      make: 'NIKON CORPORATION',
      model: 'NIKON D90',
      name: 'NIKON CORPORATION, NIKON D90',
      exposure_time: '1/4000',
      aperture: '2.8',
      focal_length: '40.0',
      iso: 1000,
    },
    location: {
      name: 'Adjara, Georgia',
      city: null,
      country: 'Georgia',
      position: {
        latitude: 41.6005626,
        longitude: 42.0688382999999,
      },
    },
    views: 38338771,
    downloads: 463173,
  },
  {
    id: 'kKrfPaKgE1c',
    slug: 'white-fog-over-pine-trees-on-mountain-kKrfPaKgE1c',
    alternative_slugs: {
      en: 'white-fog-over-pine-trees-on-mountain-kKrfPaKgE1c',
      es: 'niebla-blanca-sobre-los-pinos-en-la-montana-kKrfPaKgE1c',
      ja: '山の松の木にかかった白い霧-kKrfPaKgE1c',
      fr: 'brouillard-blanc-au-dessus-des-pins-sur-la-montagne-kKrfPaKgE1c',
      it: 'nebbia-bianca-sopra-i-pini-sulla-montagna-kKrfPaKgE1c',
      ko: '산의-소나무-위로-흰-안개-kKrfPaKgE1c',
      de: 'weisser-nebel-uber-kiefern-auf-berg-kKrfPaKgE1c',
      pt: 'nevoeiro-branco-sobre-pinheiros-na-montanha-kKrfPaKgE1c',
    },
    created_at: '2015-10-19T20:13:29Z',
    updated_at: '2024-04-01T08:36:02Z',
    promoted_at: '2015-10-19T20:13:29Z',
    width: 6000,
    height: 4000,
    color: '#f3f3f3',
    blur_hash: 'L$LN*|_4M|of~qofIUj[R+IUf6t7',
    description: 'Fog over winter hillside',
    alt_description: 'white fog over pine trees on mountain',
    breadcrumbs: [],
    urls: {
      raw: 'https://images.unsplash.com/photo-1445285303476-2f3b16d67b7a?ixid=M3w1OTQwMTR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTM4OTA2ODV8&ixlib=rb-4.0.3',
      full: 'https://images.unsplash.com/photo-1445285303476-2f3b16d67b7a?crop=entropy&cs=srgb&fm=jpg&ixid=M3w1OTQwMTR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTM4OTA2ODV8&ixlib=rb-4.0.3&q=85',
      regular:
        'https://images.unsplash.com/photo-1445285303476-2f3b16d67b7a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w1OTQwMTR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTM4OTA2ODV8&ixlib=rb-4.0.3&q=80&w=1080',
      small:
        'https://images.unsplash.com/photo-1445285303476-2f3b16d67b7a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w1OTQwMTR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTM4OTA2ODV8&ixlib=rb-4.0.3&q=80&w=400',
      thumb:
        'https://images.unsplash.com/photo-1445285303476-2f3b16d67b7a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w1OTQwMTR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTM4OTA2ODV8&ixlib=rb-4.0.3&q=80&w=200',
      small_s3:
        'https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1445285303476-2f3b16d67b7a',
    },
    links: {
      self: 'https://api.unsplash.com/photos/white-fog-over-pine-trees-on-mountain-kKrfPaKgE1c',
      html: 'https://unsplash.com/photos/white-fog-over-pine-trees-on-mountain-kKrfPaKgE1c',
      download:
        'https://unsplash.com/photos/kKrfPaKgE1c/download?ixid=M3w1OTQwMTR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTM4OTA2ODV8',
      download_location:
        'https://api.unsplash.com/photos/kKrfPaKgE1c/download?ixid=M3w1OTQwMTR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MTM4OTA2ODV8',
    },
    likes: 1335,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {
      wallpapers: {
        status: 'approved',
        approved_on: '2020-04-29T08:21:46Z',
      },
      nature: {
        status: 'approved',
        approved_on: '2020-04-29T08:21:44Z',
      },
    },
    asset_type: 'photo',
    user: {
      id: 'hpAiOic6Ct0',
      updated_at: '2024-03-09T23:43:24Z',
      username: 'albertorestifo',
      name: 'Alberto Restifo',
      first_name: 'Alberto',
      last_name: 'Restifo',
      twitter_username: null,
      portfolio_url: 'https://alberto.restifo.dev',
      bio: "I do my best to be the happiest in the room. I love mountains. When I'm not wearing hiking boots, I'm a programmer.",
      location: 'Madrid, Spain',
      links: {
        self: 'https://api.unsplash.com/users/albertorestifo',
        html: 'https://unsplash.com/@albertorestifo',
        photos: 'https://api.unsplash.com/users/albertorestifo/photos',
        likes: 'https://api.unsplash.com/users/albertorestifo/likes',
        portfolio: 'https://api.unsplash.com/users/albertorestifo/portfolio',
        following: 'https://api.unsplash.com/users/albertorestifo/following',
        followers: 'https://api.unsplash.com/users/albertorestifo/followers',
      },
      profile_image: {
        small:
          'https://images.unsplash.com/profile-1501480298034-b3855154dd8e?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32',
        medium:
          'https://images.unsplash.com/profile-1501480298034-b3855154dd8e?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64',
        large:
          'https://images.unsplash.com/profile-1501480298034-b3855154dd8e?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128',
      },
      instagram_username: null,
      total_collections: 0,
      total_likes: 4,
      total_photos: 40,
      total_promoted_photos: 14,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: false,
      social: {
        instagram_username: null,
        portfolio_url: 'https://alberto.restifo.dev',
        twitter_username: null,
        paypal_email: null,
      },
    },
    exif: {
      make: 'SONY',
      model: 'ILCE-7',
      name: 'SONY, ILCE-7',
      exposure_time: '1/200',
      aperture: null,
      focal_length: null,
      iso: 400,
    },
    location: {
      name: null,
      city: null,
      country: null,
      position: {
        latitude: null,
        longitude: null,
      },
    },
    views: 21233073,
    downloads: 246472,
  },
]
